import { CARD_IDS, GOD_IDS, type CardId, type GodId } from "@bc/shared";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { parseArgs } from "node:util";
import { RandomStrategy } from "./strategies/random.js";
import { runGame, type GameResult } from "./runGame.js";

type Opts = { games: number; seed: string; players: number; out: string };

function parseOpts(): Opts {
  const { values } = parseArgs({
    options: {
      games: { type: "string", default: "10000" },
      seed: { type: "string", default: "report" },
      players: { type: "string", default: "2" },
      out: { type: "string", default: "Docs/design/05-current-metrics.md" },
    },
    allowPositionals: false,
  });
  return {
    games: parseInt(values.games!, 10),
    seed: values.seed!,
    players: parseInt(values.players!, 10),
    out: values.out!,
  };
}

function main(): void {
  const opts = parseOpts();
  const start = performance.now();
  const results: GameResult[] = [];
  for (let g = 0; g < opts.games; g++) {
    const seed = `${opts.seed}-${g}`;
    const playerStrategies = [];
    for (let p = 0; p < opts.players; p++) {
      const god = GOD_IDS[(g * opts.players + p) % GOD_IDS.length]!;
      playerStrategies.push({
        id: `p${p + 1}`,
        name: `P${p + 1}-${god}`,
        strategy: new RandomStrategy(`${seed}-${p}`),
        forceGod: god,
      });
    }
    results.push(runGame({ seed, playerStrategies }));
  }
  const elapsed = performance.now() - start;

  const cardPlays: Record<CardId, number> = empty();
  const cardWins: Record<CardId, number> = empty();
  const godPlays: Record<GodId, number> = emptyGod();
  const godWins: Record<GodId, number> = emptyGod();
  let totalRounds = 0;
  let totalFightingRounds = 0;
  const terminationCounts: Record<string, number> = {};

  for (const r of results) {
    totalRounds += r.rounds;
    totalFightingRounds += r.phases.fighting;
    terminationCounts[r.terminatedBy] = (terminationCounts[r.terminatedBy] ?? 0) + 1;
    for (const p of r.players) {
      if (p.god) {
        godPlays[p.god] += 1;
        if (p.id === r.winner) godWins[p.god] += 1;
      }
      const seen = new Set<CardId>();
      for (const c of p.cardsPlayedList) {
        if (seen.has(c)) continue;
        seen.add(c);
        cardPlays[c] += 1;
        if (p.id === r.winner) cardWins[c] += 1;
      }
    }
  }

  const md = renderMarkdown({
    opts,
    elapsed,
    results,
    cardPlays,
    cardWins,
    godPlays,
    godWins,
    totalRounds,
    totalFightingRounds,
    terminationCounts,
  });

  mkdirSync(dirname(opts.out), { recursive: true });
  writeFileSync(opts.out, md);
  console.log(`Wrote ${opts.out} (${results.length} games, ${elapsed.toFixed(0)}ms)`);
}

type RenderInput = {
  opts: Opts;
  elapsed: number;
  results: GameResult[];
  cardPlays: Record<CardId, number>;
  cardWins: Record<CardId, number>;
  godPlays: Record<GodId, number>;
  godWins: Record<GodId, number>;
  totalRounds: number;
  totalFightingRounds: number;
  terminationCounts: Record<string, number>;
};

function renderMarkdown(input: RenderInput): string {
  const total = input.results.length;
  const date = new Date().toISOString().slice(0, 10);

  const godRows = GOD_IDS.map((g) => {
    const plays = input.godPlays[g];
    const wins = input.godWins[g];
    const wr = plays > 0 ? wins / plays : 0;
    return { g, plays, wins, wr };
  }).sort((a, b) => b.wr - a.wr);

  const cardRows = (CARD_IDS as readonly CardId[])
    .map((c) => {
      const plays = input.cardPlays[c];
      const wins = input.cardWins[c];
      const wr = plays > 0 ? wins / plays : 0;
      const pickRate = plays / Math.max(1, total * input.opts.players);
      return { c, plays, wins, wr, pickRate };
    })
    .sort((a, b) => b.wr - a.wr);

  const wrValues = godRows.map((r) => r.wr * 100);
  const spread = Math.max(...wrValues) - Math.min(...wrValues);

  const lines: string[] = [];
  lines.push("<!-- AUTO-GENERATED by `pnpm sim-report` (or `./run.sh report`). Do not hand-edit. -->");
  lines.push("");
  lines.push("# Current metrics");
  lines.push("");
  lines.push(`*Generated ${date} from a ${total.toLocaleString()}-game simulation, ${input.opts.players} players each, gods rotated for unbiased measurement.*`);
  lines.push("");
  lines.push(`- Seed prefix: \`${input.opts.seed}\``);
  lines.push(`- Throughput: ${((total / input.elapsed) * 1000).toFixed(0)} games/sec (${input.elapsed.toFixed(0)}ms total)`);
  lines.push(`- Avg total rounds per game: ${(input.totalRounds / total).toFixed(1)}`);
  lines.push(`- Avg fighting rounds: ${(input.totalFightingRounds / total).toFixed(1)}`);
  lines.push(`- Termination breakdown: ${Object.entries(input.terminationCounts).map(([k, v]) => `${k}=${v}`).join(", ")}`);
  lines.push("");
  lines.push("## God win rates");
  lines.push("");
  lines.push(`Spread: **${spread.toFixed(1)}pp** (target: under 5pp).`);
  lines.push("");
  lines.push("| God | Win % | Plays | Wins |");
  lines.push("|---|---:|---:|---:|");
  for (const r of godRows) {
    lines.push(`| ${r.g} | ${(r.wr * 100).toFixed(1)}% | ${r.plays} | ${r.wins} |`);
  }
  lines.push("");
  lines.push("## Card win contribution");
  lines.push("");
  lines.push("Win % = fraction of games where the player who played the card went on to win the game. Ranked descending. Pick % is the per-player chance the card was played in any given game.");
  lines.push("");
  lines.push("| Card | Win % | Pick % | Plays | Wins |");
  lines.push("|---|---:|---:|---:|---:|");
  for (const r of cardRows) {
    lines.push(
      `| ${r.c} | ${(r.wr * 100).toFixed(1)}% | ${(r.pickRate * 100).toFixed(1)}% | ${r.plays} | ${r.wins} |`,
    );
  }
  lines.push("");
  lines.push("## How to interpret");
  lines.push("");
  lines.push("- **God spread under 5pp** is the target for a balanced 6-god roster under random play.");
  lines.push("- **Card win % around 50%** is neutral. Damage cards naturally trend higher (55–65%) because the player who deals damage tends to win. >70% suggests an oppressive card; <40% suggests dead weight.");
  lines.push("- **Pick rate ~ 1/24** for fully random play is the floor. Strategy bias may push some cards higher.");
  lines.push("- See [04-card-catalog.md](./04-card-catalog.md) for current numerical effects per card.");
  lines.push("- Refresh this file: `./run.sh report` (or `pnpm --filter @bc/simulator run report`).");

  return lines.join("\n") + "\n";
}

function empty(): Record<CardId, number> {
  const r = {} as Record<CardId, number>;
  for (const c of CARD_IDS) r[c] = 0;
  return r;
}

function emptyGod(): Record<GodId, number> {
  const r = {} as Record<GodId, number>;
  for (const g of GOD_IDS) r[g] = 0;
  return r;
}

main();
